#!/bin/python3

import math
import os
import random
import re
import sys

def sockMerchant(n, ar):
    counter = {} 
    for i in ar:
        if i in counter:
            counter[i] = counter[i] + 1
        else:
            counter[i] = 1
    pair_socks = 0
    for x in counter.values():
        pair_socks = pair_socks + int(x / 2)
    
    return pair_socks
        
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    ar = list(map(int, input().rstrip().split()))

    result = sockMerchant(n, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
